dist: trusty
install:
- sudo rm -r /usr/local/clang-3.5.0
- wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
- sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main"
- sudo apt-get update
- sudo apt-get install llvm-3.8 llvm-3.8-dev clang-3.8 clang-3.8-dev libc++-dev
- sudo ln -sf /usr/bin/clang-3.8 /usr/bin/clang
- sudo ln -sf /usr/bin/llc-3.8 /usr/bin/llc
- sudo ln -sf /usr/bin/opt-3.8 /usr/bin/opt
script:
- make
